# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
      - main
      - dev

pool:
  name: 'MySelfHostedpool'
  demands: []

steps:

  # prepare sonar cloud
  - task: SonarCloudPrepare@3
    inputs:
      SonarCloud: 'SonarCloudServiceConnection'
      organization: 'devanshi-rangras'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'Devanshi-Rangras_sample-job-portal'
      cliProjectName: 'JobPortal'
      cliSources: '.'
  
  #setup jdk for spring boot backend
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '21'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'LocalDirectory'
      jdkFile: 'C:\Program Files\Eclipse Adoptium\jdk-21.0.8.9-hotspot\bin'
  
  #Build & test backend with Maven
  - script: |
      cd backend
      mvn clean verify
    displayName: 'Build & Test Backend (Maven)'

  #Setup Node.js for frontend 
  - task: NodeTool@0 
    inputs: 
      versionSpec: '18.x' 
    displayName: 'Install Node.js'

  #Build & test frontend 
  - script: | 
      cd frontend 
      npm install 
      npm run build 
      npm test -- --coverage || echo "No tests found" 
    displayName: 'Build & Test Frontend'

  #Run SonarCloud Analysis 
  - task: SonarCloudAnalyze@3

  #Publish results (Quality Gate) 
  - task: SonarCloudPublish@3
    inputs: 
      pollingTimeoutSec: '300'